#!/bin/bash -eu
function dbg() { echo -e "\\e[94m${*}\\e[39m"; }
function inf() { echo -e "\\e[97m${*}\\e[39m"; }
function out() { echo -e "\\e[32m${*}\\e[39m"; }
function wrn() { echo -e "\\e[93m${*}\\e[39m" 1>&2; }
function err() { echo -e "\\e[31m${*}\\e[39m" 1>&2; }
function fail() { err "${@}"; exit 254; }

SCRIPT=$(readlink -f "${0}")
SCRIPT_NAME=$(basename "${SCRIPT}")

DEFAULT_EXECUTOR="docker"
DEFAULT_IMAGE="debian:sid-slim"

show_help() {
inf "Usage: ${SCRIPT_NAME} [OPTIONS] 

Register new gitlab runner.

Options:
    -N <name>       runner name (mandatory)
    -U <url>        gitlab url (mandatory)
    -T <token>      gitlab token (mandatory)
    -e <executor>   executor (docker or shell, default ${DEFAULT_EXECUTOR})
    -i <image>      default image (default ${DEFAULT_IMAGE})
    -t <tags>       runner tags (default same as executor)
    -h,-?           display this help and exit

Environments:
    NAME, URL, TOKEN, EXECUTOR, IMAGE, TAGS

Examples:
    ${SCRIPT_NAME} -N runner-with-docker -U our.gitlab.com -T token-value
    NAME=runner-with-docker URL=our.gitlab.com TOKEN=token-value ${SCRIPT_NAME}
"
        exit 1
}

OPTIND=1
while getopts "N:T:U:e:i:t:h" OPT; do
    case "${OPT}" in
        "N")    NAME="${OPTARG}";;
        "T")    TOKEN="${OPTARG}";;
        "U")    URL="${OPTARG}";;
        "e")    EXECUTOR="${OPTARG}";;
        "i")    IMAGE="${OPTARG}";;
        "t")    TAGS="${OPTARG}";;
        "h"|"?")show_help;;
        "*")    echo "Unknown option: -${OPTARG}. Run with -h to display help";;
    esac
done
shift "$((OPTIND-1))"   

if [[ ! ${NAME+x} ]]; then fail "Missing -N <name>"; fi
if [[ ! ${TOKEN+x} ]]; then fail "Missing -T <token>"; fi
if [[ ! ${URL+x} ]]; then fail "Missing -U <url>"; fi
EXECUTOR="${EXECUTOR:-"${DEFAULT_EXECUTOR}"}"
TAGS="${TAGS:-"${EXECUTOR}"}"
IMAGE="${IMAGE:-"${DEFAULT_IMAGE}"}"


REGEX="^[a-z0-9]([a-z0-9-]*[a-z0-9]+)*$"
if [[ ! "${NAME}" =~ ${REGEX} ]]; then
    fail "Runner name ${NAME} does not match ${REGEX}"
fi
REGEX="^(docker|shell)$"
if [[ ! "${EXECUTOR}" =~ ${REGEX} ]]; then
    fail "Unsupported runner executor: ${EXECUTOR}"
fi


gitlab-runner status 2>/dev/null || (inf "Starting runner"; gitlab-runner start)
inf "Registering runner as ${NAME}"
gitlab-runner register \
    --non-interactive \
    --executor "${EXECUTOR}" \
    --docker-image "${IMAGE:-"debian:sid-slim"}" \
    --url "${URL}" \
    --registration-token "${TOKEN}" \
    --name "${NAME}" \
    --tag-list "${TAGS}" \
    --run-untagged \
    --locked="${LOCKED:-"false"}"
trap handleSignal EXIT
unregister() {
    trap - EXIT
    echo
    inf "Unregistering runner ${NAME}"
    gitlab-runner unregister \
        --name "${NAME}"
}
handleSignal() {
    unregister    
    exit 1
}
while true; do
    gitlab-runner status
    sleep 5
done

unregister
